tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: "t5-base"
  model_max_length: 16

encoder:
  _target_: multi_modal_transformers.tokenizers.text.t5_base.T5Tokenizer

